apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apicurio-registry
    component: apicurio-registry-api
  name: apicurio-registry-api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: apicurio-registry-api
  template:
    metadata:
      labels:
        app: apicurio-registry
        component: apicurio-registry-api
    spec:
      containers:
      - image: quay.io/apicurio/apicurio-registry-sql:latest-snapshot
        name: apicurio-registry-api
        ports:
          - name: web
            containerPort: 8080
            protocol: TCP
        env:
          - name: LOG_LEVEL
            value: DEBUG
          - name: REGISTRY_LOG_LEVEL
            value: DEBUG
          - name: ENABLE_ACCESS_LOG
            value: "true"
          - name: QUARKUS_PROFILE
            value: prod
          - name: CORS_ALLOWED_ORIGINS
            value: "*"

          - name: AUTH_ENABLED
            value: "true"
          - name: KEYCLOAK_URL
            value: http://keycloak.keycloak.svc.cluster.local:8080
          - name: KEYCLOAK_REALM
            value: apicurio
          - name: KEYCLOAK_API_CLIENT_ID
            value: registry-api

          - name: REGISTRY_DATASOURCE_URL
            value: jdbc:postgresql://apicurio-registry-postgresql:5432/apicuriodb
          - name: REGISTRY_DATASOURCE_USERNAME
            value: pguser
          - name: REGISTRY_DATASOURCE_PASSWORD
            value: pgpass12345
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: /apis/registry/v2/system/info
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /apis/registry/v2/system/info
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apicurio-registry
    template: apicurio-registry-api
  name: apicurio-registry-api
spec:
  selector:
    component: apicurio-registry-api
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: apicurio-registry
    template: apicurio-registry-api
  name: apicurio-registry-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: api-registry-api.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: apicurio-registry-api
                port:
                  number: 8080
