version: 2
updates:
- package-ecosystem: maven
  directory: "/hub"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
      hub-dependencies:
        patterns:
          - "*"

- package-ecosystem: npm
  directory: "/ui"
  schedule:
    interval: daily
  groups:
      ui-dependencies:
        patterns:
          - "*"
  open-pull-requests-limit: 10
  versioning-strategy: increase

- package-ecosystem: npm
  directory: "/validator"
  schedule:
    interval: daily
  groups:
      validator-dependencies:
        patterns:
          - "*"
  open-pull-requests-limit: 10
  versioning-strategy: increase
