apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:22.0.3
          args: [ "start", "--import-realm", "--db", "postgres", "--db-url", "jdbc:postgresql://keycloak-postgresql:5432/keycloakdb", "--db-username", "pguser", "--db-password", "pgpass12345" ]
          volumeMounts:
            - name: config-volume
              mountPath: /opt/keycloak/data/import
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_PROXY
              value: edge
            - name: KC_HOSTNAME_URL
              value: http://keycloak.local

            - name: KC_DATABASE
              value: postgres
            - name: KC_STORAGE
              value: jpa
            - name: KC_DATABASE_URL
              value: jdbc:postgresql://keycloak-postgresql:5432/keycloakdb
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
      volumes:
        - name: config-volume
          configMap:
            name: keycloak-realm-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
    template: keycloak
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: keycloak
    template: keycloak
  name: keycloak
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: keycloak.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
