apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apicurio-designer
    component: apicurio-designer-ui
  name: apicurio-designer-ui
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: apicurio-designer-ui
  template:
    metadata:
      labels:
        app: apicurio-designer
        component: apicurio-designer-ui
    spec:
      containers:
      - image: quay.io/apicurio/apicurio-api-designer-ui:latest-snapshot
        name: apicurio-designer-ui
        ports:
          - name: web
            containerPort: 8080
            protocol: TCP
        env:
          - name: DESIGNER_API_URL
            value: http://designer-api.local/apis/designer/v0

          - name: DESIGNER_AUTH_TYPE
            value: oidc
          - name: DESIGNER_AUTH_URL
            value: http://keycloak.local/realms/apicurio
          - name: DESIGNER_AUTH_CLIENT_ID
            value: designer-ui
          - name: DESIGNER_AUTH_REDIRECT_URL
            value: http://designer.local/
        resources:
          limits:
            cpu: 250m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apicurio-designer
    template: apicurio-designer-ui
  name: apicurio-designer-ui
spec:
  selector:
    component: apicurio-designer-ui
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: apicurio-designer
    template: apicurio-designer-ui
  name: apicurio-designer-ui
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: designer.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: apicurio-designer-ui
                port:
                  number: 8080
