apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microcks-postman
  name: microcks-postman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microcks-postman
  template:
    metadata:
      labels:
        app: microcks-postman
    spec:
      containers:
        - name: microcks-postman
          image: quay.io/microcks/microcks-postman-runtime:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1200Mi
            requests:
              cpu: 200m
              memory: 400Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: microcks-postman
  name: microcks-postman
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: microcks-postman
  type: ClusterIP
