name: Build Validator Image (Snapshot)
on:
  push:
    paths:
      - 'validator/**'
    branches: [ main, '[1-9].[0-9].x' ]
  workflow_dispatch:

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PLATFORMS: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
  IMAGE_ORG: apicurio
  IMAGE_NAME: apicurio-api-lifecycle-validator
  IMAGE_TAG: latest-snapshot

jobs:
  build-image:
    name: Build/Push Validator
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'Apicurio' && !contains(github.event.*.labels.*.name, 'DO NOT MERGE')
    steps:
      - name: Checkout Code with Ref '${{ github.ref }}'
        uses: actions/checkout@v3

      # Open-Source Machine emulator that allows you to emulate multiple CPU architectures on your machine
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Docker CLI plugin for extended build capabilities with BuildKit
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Login to Quay.io Registry
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Build and Publish Docker Image (Validator)
        uses: docker/build-push-action@v2
        with:
          context: ./validator
          file: ./validator/Dockerfile
          platforms: ${{env.PLATFORMS}}
          push: true
          tags: |
            docker.io/${{env.IMAGE_ORG}}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
            quay.io/${{env.IMAGE_ORG}}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
