apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apicurio-lifecycle
    component: apicurio-lifecycle-validator
  name: apicurio-lifecycle-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      component: apicurio-lifecycle-validator
  template:
    metadata:
      labels:
        app: apicurio-lifecycle
        component: apicurio-lifecycle-validator
    spec:
      containers:
      - image: apicurio/apicurio-lifecycle-validator:latest
        name: apicurio-lifecycle-validator
        ports:
          - name: web
            containerPort: 3000
            protocol: TCP
        env:
          - name: LOG_LEVEL
            value: DEBUG
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apicurio-lifecycle
    component: apicurio-lifecycle-validator
  name: apicurio-lifecycle-validator
spec:
  selector:
    component: apicurio-lifecycle-validator
  ports:
    - name: web
      port: 3000
      protocol: TCP
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: apicurio-lifecycle
    component: apicurio-lifecycle-validator
  name: apicurio-lifecycle-validator
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: validator.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: apicurio-lifecycle-validator
                port:
                  number: 3000
